### ISSUE TITLE
Ask if there will be a linux version in the future

### ISSUE THREAD

**Issue by wz18207** [m4saka/kshootmania-v1#11]
Thanks for the game provided on the https://www.kshootmania.com. I can play a lot of fun KMS storefronts and songs very happily. If the highest score is 5 points, I would rather score 10 points.
Here I want to ask if I only found the windows version on the official website. I would like to ask if there will be a Linux version of the game in the future.

**Comment by m4saka** [comment]
It is planned to have linux support in the next major version (v2).

Currently, you can use Wine to play the game with Linux.
It works quite well except for Internet Ranking System.
