### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by prescientmoon** [m4saka/kshootmania-v1#23]
I downloaded the game and tried running it, but I get this error: 
![image](https://user-images.githubusercontent.com/39400800/102083579-7782cf80-3e1c-11eb-86e6-d764ffee57df.png)

**Comment by m4saka** [comment]
@Mateiadrielrafael,
Did you check the troubleshooting page below?

https://www.kshootmania.com/en/troubleshooting.html
![image](https://user-images.githubusercontent.com/14288724/102096550-30223080-3e68-11eb-96d1-8eef58826fd4.png)

**Comment by prescientmoon** [comment]
Thanks
