### ISSUE TITLE
zoom_top=200 で垂直にならないのは仕様ですか

### ISSUE THREAD

**Issue by gckohaku** [m4saka/kshootmania-v1#29]
レーンズーム (上部) の挙動が判定ラインを中心軸にして回転する仕様とのことなので、zoom_top とレーンの角度の関係を調べておりました。
-400 辺りと 800 辺りでレーンが完全に見えなくなることから、その中間である 200 に設定すればレーンが垂直になるかと思ったのですが、垂直にはなりませんでした。
これは想定通りの挙動なのでしょうか。また想定通りの挙動の場合は、レーンが垂直になる zoom_top の値を算出する方法があれば教えて頂けると幸いです。

**Comment by m4saka** [comment]
大変申し訳ございませんが、プログラム自体に直接関係する点以外についてのご質問は掲示板へ新しいスレッドを立てて投稿していただけると助かります。
https://bbs.kshootmania.com/
